#+SETUPFILE: ../style/default.setup
#+INCLUDE: ../style/latex.setup

* Hydrodynamics

** Hydrodynamic equations

My notes: "Notability::Research:Topics:19. Fluid dynamics"

*Summary*
We introduce a /material derivative/ $D/Dt = \partial/\partial t + \mathbf{v} \cdot \nabla$. It is the derivative following the gas flow, defined as $D Q / Dt = \frac{Q(t+\delta t, {\bf x} + {\bf v}\delta t) - Q(t, {\bf x})}{\delta t}$. Then, the /Euler equations of fluid/ is easily represented as
\begin{align}
\frac{D \rho}{D t} &= - \rho \nabla \cdot {\bf v} \\
\frac{D {\bf v}}{D t} &= - \frac{\nabla p}{\rho} + {\bf g} \\
\frac{D e}{D t} &= - \frac{\nabla \cdot (p {\bf v})}{\rho}
\end{align}
The first equation, the equation of continuity, can be derived by inspecting a volume of fluid, in which the outflow rate equals the change in mass, and we obtain $\partial \rho / \partial t + \nabla \cdot (\rho {\bf v}) = 0$. The conversion between the two different form can be acheived by using the expansion of $\nabla \cdot (\rho {\bf v})$. 

** Time Scales
   :PROPERTIES:
   :CUSTOM_ID: subsec:time
   :END:

*** Free fall time
    :PROPERTIES:
    :CUSTOM_ID: free-fall-time
    :END:

Assume mean molecular weight $\mu = 1.4$, the global free-fall time of a
cloud with particle number density $n$ is given by $$\label{eq:ff}
t_{{\rm ff}} = \sqrt{\frac{3\pi}{32G\rho_{0}}} \approx 1.376~{\rm Myr}
\cdot \left(\frac{n}{10^3 \si{cm^{-3}}}\right)^{-1/2}$$

*** Sound speed
    :PROPERTIES:
    :CUSTOM_ID: sound-speed
    :END:
The /sound speed/ is given by
$$
c_{s}=\sqrt{\frac{\gamma p_{0}}{\rho_{0}}}
= \sqrt{\frac{\gamma kT}{\mu m_{H}}}
$$
The /isothermal sound speed/ is therefore
$$
c_s = \sqrt{\frac{kT}{\mu m_{H}}} = 0.29\,\si{km/s} \; \left( \frac{T_1}{\mu} \right)^{1/2} = 9.1\,\si{km/s} \; \left( \frac{T_4}{\mu} \right)^{1/2} 
$$
where $\mu$ is the mean particle weight. Note that for ionized hydrogen, $\mu = 0.5$ and $c_s = 13\,\si{km/s}$ at $10^4$ K.

*** Alfven wave
    :PROPERTIES:
    :CUSTOM_ID: alfven-wave
    :END:

/(Need to learn)/ The Alfven velocity is given by
$v_{{\rm A}}=B_{0}/\sqrt{4\pi\rho_{0}}$ (in cgs). Therefore, the Alfven
wave crossing time is
$t_{{\rm act}}=L/v_{{\rm A}}=L\sqrt{4\pi\rho_{0}}/B_{0}$.

In He et al. (2019), and , therefore $v_A / \sigma$ = 0.2, where
$\sigma$ is the turbulence velocity dispersion.

*** Velocity dispersion
    :PROPERTIES:
    :CUSTOM_ID: velocity-dispersion
    :END:

** Jeans Mass
   :PROPERTIES:
   :CUSTOM_ID: jeans-mass
   :END:

$$M_{\rm J} \equiv \frac{4\pi}{3}\lambda_{\rm J}^3 \rho
  \approx 20 \msun \cdot \left( \frac{T}{10 {\rm K}}
  \right)^{3/2} \left( \frac{n}{100\,{\rm cm}^{-3}} \right) ^{-1/2}$$


** Bondi Accretion
   :PROPERTIES:
   :CUSTOM_ID: subsec:bondi
   :END:

**** Hoyle and Lyttleton accretion
     :PROPERTIES:
     :CUSTOM_ID: hoyle-and-lyttleton-accretion
     :END:

A star moving through gas cloud. Assuming a ballistic orbit for accreted
particles, we get a impact factor $$\label{eq:1}
\zeta_{HL} = \frac{2GM}{v_{\infty}^2}.$$ and accretion rate (mass flux)
$$\label{eq:1}
\dot{M}_{HL} = \pi \zeta_{HL}^2 v_{\infty} \rho_{\infty} = \frac{4\pi G^2M^2\rho_{\infty}}{v_{\infty}^3}.$$

**** Bondi Accretion
     :PROPERTIES:
     :CUSTOM_ID: bondi-accretion
     :END:

A Bondi radius may be defined as $$r_B = \frac{GM}{c_{s}^2(r_B)}$$ Flow
outside is subsonic and the density is almost uniform. This ends up with
a Bondi accretion rate
$$\dot{M}_B = 4 \pi r_B^2 c_s \rho_{\infty} = \frac{4\pi
    G^{2}M^{2}\rho_{\infty}}{c_s^{3}}$$ And interpolation formula would
be $$\label{eq:bondi}
\dot{M}_B = 4 \pi r_B^2 c_s \rho_{\infty} = \frac{4\pi
  G^{2}M^{2}\rho_{\infty}}{(c_\infty^2 + v_{\infty}^2)^{3/2} }.$$

** Other topics
   :PROPERTIES:
   :CUSTOM_ID: subsec:other
   :END:

*** Viscosity

*Definition of viscosity*: The fource $F$ acting on the top plate of a fluid is proportional to the gradient of the speed $u$ and the area $A$ of the plate:
$$
F = \mu A \frac{\partial u}{\partial y},
$$
$\mu$ is the /dynamic viscosity/ of the fluid, with units of Pa s (pascal-second). The /kinematic viscosity/ is defined as the ratio fo the viscosity $\mu$ to the fluid density:
$$
\nu = \frac{\mu}{\rho},
$$
with the dimension of $L^2/T$. 

*** Reynolds Number
     :PROPERTIES:
     :CUSTOM_ID: reynolds-number
     :END:

$\mathcal{R}=LV/\nu$, where $L$ is the typical length of the object, $V$ is the typical fluid velocity, and $\nu$ is the viscosity of the fluid. Imagine two different fluid flows around two geometrically similar objects. If these two systems have the same Reynolds number, then the flow patterns should be similar. This is called the law of similarity (Reynolds 1883). Systems with low Reynolds number are dominated by viscosity.

There is also the /magnetic Reynolds number/ where the vescosity is replaced with the magnetic diffusivity $\lambda = c^2 / 4 \pi \sigma$. See Sec. 14.2 of of Choudhuri (1998). 

* MHD

** MHD

Within the confines of the magnnetohydrodynamics of a single-component condducting fluid, the material effects of electromagnetic fields enter as two terms:
#+begin_quote
Lorentz force per unit volume: ${\bf j} \times {\bf B} / c = (\nabla \times {\bf B}) \times {\bf B} / 4\pi$.\\
Heat production per volume by Ohmic dissipation: $j^2 / \sigma = \eta | \nabla \times {\bf B} |^2 / 4\pi$  
#+end_quote

Therefore, the equation of continuity is not changed; the equation of motion has to change by adding a magnetic body force, ${\bf j} \times {\bf B} / \rho c$, where ${\bf j} = (c/4\pi) \nabla \times {\bf B}$  is the electric current density. The energy equation has to add an /Ohmic heating/ term, ${\bf j}^2 / \sigma$ 

Reference: Sec. 14.1 of Choudhuri (1998); page 302 of Shu, F. "Gas Dynamics".

* Codes
  :PROPERTIES:
  :CUSTOM_ID: hydrodynamic Al-simulations
  :END:

** Hydro Methods and Codes, Summary
   :PROPERTIES:
   :CUSTOM_ID: methods-and-code
   :END:

Specification of the flow field:

- Euler approach: The fluid properties are written as functions of space and times. Cons: limited dynamic range.

- Lagrangian approach: Pieces of the fluid are "tagged". The fluid flow properties are determined by tracking the motion and properties of the particles as they move in time.

- Smooth Particles Hydrodynamics (SPH): an intermediate solution. Follows the Lagrangian evolution of the flow, in which resolution elements are defined as appropriate averages over 50 neighboring particles.

Methods of N-body code:

- Particle-Mesh: fastest, but only support dynamical range of $10^3$.

- P3M: higher spatial resolution, but significant increase in CPU time.

- AP3M: rectangular grids is placed in clustered regions to apply PM
  solver.

- AMR: Generalization of both AP3M and TREE. e.g. ART.

N-body code:

- ART:

	  - The first implementation of a grid-based high-resolution N-body code.

	  - AMR: recursively in a fully adaptive manner in the regions where the density exceeds a predefined threshold. Mean number of particles per cell remains roughly constant (around 10).

	  - "Quasi-Lagrangian" approach ensures two-body relaxation remains unimportant.

	  - The mesh structure is not created at every time step, but is properly adjusted to the evolving particle distribution.

** RAMSES
   :PROPERTIES:
   :CUSTOM_ID: sec:ramses
   :END:

*** Summary
    :PROPERTIES:
    :CUSTOM_ID: summary
    :END:

- The AMR grid is built on a tree structure.

- The hydrodynamic solver is based on a second order Godunov method, to solve the Euler equation.

- Refinement strategy retained for cosmological simulations is based on a "quasi-Lagrangian" mesh evolution.

*** Features
    :PROPERTIES:
    :CUSTOM_ID: features
    :CLASS: unnumbered
    :END:

- Coupling a tree-based AMR hydrodynamical scheme to the N-body solver developed for the ART code.

- Hydrodynamical solver: second-order Godunov scheme for perfect gases.

*** M1 closure
    :PROPERTIES:
    :CUSTOM_ID: m1-closure
    :END:

Assume that the radiation field is locally a dipole. The photon distribution function is the Lorentz transform of a Planckian distribution. Dipole is aligned locally to the radiation flux.

Under M1, the radiative transfer equation is turned into an hyperbolic system of conservation laws with source terms.

*** Cooling Function
    :PROPERTIES:
    :CUSTOM_ID: cooling-function
    :END:

Possibly a big issue!!! I see a mu=1.4 with comments: hard set mu=1.4 to make temperature agree with Audic & Hennebelle.

1) For hydrogen and helium
	   1. In each cell, photoheating and radiative cooling of hydrogen and helium is performed by the radiative transfer module of RAMSES-RT as in Rosdahl et al. (2013).
	   2. Photoheating rate $\mathcal{H}$ is a sum of the heating contributiosn from all photoionziation events (HI, HeI, and HeII).
	   3. The primordial cooling rate $\mathcal{L}$ include various cooling processes: collisional ionizations, collisional excitations, recombinations, dielectronic recombinations, bremsstrahlung and Compton cooling.
2) For metals
	   1. 'Neutral' function N(T)
			  - Below 10^4 K: the prescription of Audit & Hennebelle (2005), which includes *carbon, oxygen and dust grains* as well as the *ambient UV background* in the ISM. This is based on the work of Wolfire et al. (1995, 2003).
					- Including cooling by
						  - fine-structure lines of CII (92 K)
						  - fine-structure lines of OI (228 and 326 K)
						  - cooling by H (Lyα line)
						  - cooling by electron recombination onto positively charged grains
					- and heating by
						  - photo-electric effect on small grains and PAHs due to the FUV galactic radiation.
					- (This might be probmatic due to the hard mu = 1.4. In Audit2005, they have no radiative transfer, so the mean particle weight is constant at mu = 1.4, while in RAMSES RT, mu is much higher(lower?) due to ionized electrons.)
			  - Above $10^4$ K: Sutherland & Dopita (1993)
	   2. 'Photoionized' cooling function
			  - a piecewise fit to Ferland (2003): $\Lambda = 3\times10^{-24}~{\rm erg~cm^3~s^{-1}}$ below 9000 K and $2.2\times10^{-22}~{\rm erg~cm^3~s^{-1}}$ above 10^5 K.
3) For H/He
	   - ...

TODO: make a curve of the cooling funciton

**** Thermal update

$$
\frac{\partial e}{\partial t} = \Gamma \equiv {\cal H} + {\cal L}
$$
where ${\cal H}$ is the photoheating rate and ${\cal L}$ is the cooling rate.

The photoheating rate ${\cal H}$ is a sum of the heating contributions form all photoionization events, calculated with the discretization into M photon groups.

The various cooling processes are collisional ionizations/excitations, recombinations, dielectronic recombinations, bremsstrahlung, and Compton cooling.

*On-the-spot approximation* recombination-emitted photons are absorbed ‘on the spot’ by a near-lying atom (in the same cell), and hence these photon emissions cancel out by local photon absorptions. When OTSA is assumed, the gas is not photoemitting, and the case A recombination rates are replaced with case B recombination rates

**** In code

=ramses/patch/frig/main/cooling_module_frig.f90=:
- cooling_low(T, n, ref): low-T cooling
- cooling_high(T, n, ref): high-T cooling

**** Other notes

Mean particle mass, $\mu$, is correctly calculated by the function =getMu= in main/rt_cooling_module.f90:

$$
\mu = [X(1+x_{\rm HII}) + \frac{Y}{4}(1 + x_{\rm HeII} + 2x_{\rm HeIII})]^{-1}
$$
Note that in the most basic H and He senario, we have $1/\mu = X/1 + Y/4$. 

*** Sink particles

- IR feedback from accretion: exists in current version. Use ~ir_feedback~ under _Feedback parameters_. 

** N-body
   :PROPERTIES:
   :CUSTOM_ID: n-body
   :END:

The density field is computed using the 'Cloud-In-Cell' (CIC) interpolation scheme. The Poisson equation at the course level is solved using standard FFT technique. For fine levels, the potential is found using a relaxation method. The acceleration is then calculated using the 6-points finite difference approximation of the gradient. Variable time steps: a second-order midpoint scheme that reduces exactly to the leapfrog scheme for constant time steps.

** Hydro Codes
   :PROPERTIES:
   :CUSTOM_ID: hydro
   :END:

*** Fire

The FIRE simulations use the P-SPH code, a heavily modified version of Volker Springel’s Gadget 3 code whose development is led by Phil Hopkins. In addition to the explicit ISM and stellar feedback physics, P-SPH uses apressure-entropy implementation of smooth particle hydrodynamics (SPH) that resolves all the main historical discrepancies between grid-based and SPH methods, particularly for fluid mixing instabilities.

*** 
   
** Mock Observations
  :PROPERTIES:
  :CUSTOM_ID: observations
  :END:

*** Stellar population sythesis
   :PROPERTIES:
   :CUSTOM_ID: stellar-population-sythesis
   :END:

FSPS: Flexible Stellar Population Synthesis:
[[https://github.com/cconroy20/fsps]]

pythonFSPS (Flexible Stellar Population Synthesis for Python):
[[http://dfm.io/python-fsps/current/]]

Starburst99

- [[https://github.com/rjtanner/StarburstPy]]
- [[https://github.com/Morisset/pyStb99]]

[[https://users.astro.ufl.edu/~desika.narayanan/courses/ism_spring19/hw4.pdf]]

*** Filters
   :PROPERTIES:
   :CUSTOM_ID: filters
   :END:

JWST/NIRCam.F150W:
[[http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?id=JWST/NIRCam.F150W&&mode=browse&gname=JWST&gname2=NIRCam]]

Table of FSPS Filters: [[http://dfm.io/python-fsps/current/filters/]]

SDSS Filters on astroML:
[[https://www.astroml.org/book_figures/appendix/fig_sdss_filters.html]]

* Simulation Projects

** FIRE: Feedback In Realistic Environments

https://fire.northwestern.edu/


