#+SETUPFILE: ../style/default.setup
#+INCLUDE: ../style/latex.setup

* Galaxies

* The Solar Motion

http://burro.case.edu/Academics/Astr222/Galaxy/Kinematics/solarmotion.html

* Globular Cluster

** The multi-population problem

Ivan Cabrera-Ziri's slides: ([[file:~/Academics/talks/2022/2022-03-17-IvanCabrera-Ziri-changing_the_paradigm_of_GC_formation.pdf][Slides]]) 

From Ivan ([[file:~/Academics/talks/2022/2022-03-17-IvanCabrera-Ziri-changing_the_paradigm_of_GC_formation.pdf][Slides]])
#+begin_quote
Here is the slides I showed you in Aspen:

https://www.dropbox.com/s/qo36rep5jg7ob8l/changing_the_paradigm_of_GC_formation.pdf?dl=0

There are some new results that were not included there. Basically regarding the presence of multiple stellar pops. (Abundances variations) in the main sequence of young (~1.5Gyr) GCs, suggesting that they are present as well in young GCs, but they are easier to pick up when we look at the main sequence stars.

If you have any questions about this, feel free to drop me a line! And thank you for your interest in this problem, hopefully you get motivated to start working on this to help us figure this out!
#+end_quote

